import 'package:flutter_weather/common/resource_img_constant.dart';

class ImageAnimation {
  static var mapBackground = {
    '01d': ResourceImgConstant.imgDayClearSky,
    '01n': ResourceImgConstant.imgNightClearSky,
    '02d': ResourceImgConstant.imgDayPartlyCloudy,
    '02n': ResourceImgConstant.imgNightPartlyCloudy,
    '03d': ResourceImgConstant.imgDayCloudy,
    '03n': ResourceImgConstant.imgNightCloudy,
    '04d': ResourceImgConstant.imgDayCloudy,
    '04n': ResourceImgConstant.imgNightCloudy,
    '09d': ResourceImgConstant.imgDayRain,
    '09n': ResourceImgConstant.imgNightRain,
    '10d': ResourceImgConstant.imgDayRain,
    '10n': ResourceImgConstant.imgNightRain,
    '11d': ResourceImgConstant.imgDayRain,
    '11n': ResourceImgConstant.imgNightRain,
    '13d': ResourceImgConstant.imgDaySnow,
    '13n': ResourceImgConstant.imgNightSnow,
    '50d': ResourceImgConstant.imgDayFog,
    '50n': ResourceImgConstant.imgDayFog,
  };
  static var mapBackgroundChild = {
    '01d': ResourceImgConstant.imgDayClearSky24,
    '01n': ResourceImgConstant.imgNightClearSky24,
    '02d': ResourceImgConstant.imgDayPartlyCloud24,
    '02n': ResourceImgConstant.imgNightPartlyCloudy24,
    '03d': ResourceImgConstant.imgDayCloudy24,
    '03n': ResourceImgConstant.imgNightCloudy24,
    '04d': ResourceImgConstant.imgDayCloudy24,
    '04n': ResourceImgConstant.imgNightCloudy24,
    '09d': ResourceImgConstant.imgDayRain24,
    '09n': ResourceImgConstant.imgNightRain24,
    '10d': ResourceImgConstant.imgDayRain24,
    '10n': ResourceImgConstant.imgNightRain24,
    '11d': ResourceImgConstant.imgDayRain24,
    '11n': ResourceImgConstant.imgNightRain24,
    '13d': ResourceImgConstant.imgDaySnow24,
    '13n': ResourceImgConstant.imgNightSnow24,
    '50d': ResourceImgConstant.imgDayFog24,
    '50n': ResourceImgConstant.imgDayFog24,
  };
  static var mapNameIcon = {
    '01d': 'sunny',
    '01n': 'moon',
    '02d': 'sunny_cloud',
    '02n': 'moon_cloud',
    '03d': 'sunny_cloud2',
    '03n': 'moon_cloud2',
    '04d': 'sunny_cloud2',
    '04n': 'moon_cloud2',
    '09d': 'sunny_rain',
    '09n': 'moon_rain',
    '10d': 'sunny_rain',
    '10n': 'moon_rain',
    '11d': 'sunny_rain',
    '11n': 'moon_rain',
    '13d': 'sunny_snow',
    '13n': 'moon_snow',
    '50d': 'sunny_frog',
    '50n': 'moon_frog'
  };
}
